# Zadanie 1

In [9]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

#wczytuje dane
zbior = load_breast_cancer()

dane = pd.DataFrame(zbior.data, columns=zbior.feature_names)
target = pd.Series(zbior.target, name="TARGET")

#podstawowe infor
print("wymiar danych:", dane.shape)
print("liczba unikatowych wartosci w wektorze target:", target.nunique())
print()

#obliczam wariancje kolumn
wariancje = dane.var().sort_values()

#wybieram 5 kolumn z najmniejsza wariancja
kolumny_do_usuniecia = wariancje.head(5).index.tolist()

print("Proponowane kolumny do usuniecia:")
for kolumna in kolumny_do_usuniecia:
    print("-", kolumna)

#usuwam kolumny
dane_obciete = dane.drop(columns=kolumny_do_usuniecia)

#dodaje target
nowy_zbior = dane_obciete.copy()
nowy_zbior["TARGET"] = target

print()
print("Nowy wymiar danych:", nowy_zbior.shape)

#zapis do csv
nowy_zbior.to_csv("dataset_cut.csv", sep=";", index=False)

print("Zapisano do pliku dataset_cut.csv")

#podglad danych
display(nowy_zbior.head())

wymiar danych: (569, 30)
liczba unikatowych wartosci w wektorze target: 2

Proponowane kolumny do usuniecia:
- fractal dimension error
- smoothness error
- concave points error
- mean fractal dimension
- symmetry error

Nowy wymiar danych: (569, 26)
Zapisano plik dataset_cut.csv

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,radius error,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,TARGET
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,1.0950,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.5435,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.7456,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.4956,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.7572,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

Zbiór po tym jak usunąłem 5 kolumn z najmneijsza wariancją ma 26 cech zamiast 30 dzieki czemu dane sa uproszczone.

# Zadanie 4

In [12]:
from sklearn.feature_selection import SelectKBest, f_classif

#wybieram 5 najlepszych cech
wybor_cech = SelectKBest(score_func=f_classif, k=5)
nowe_dane = wybor_cech.fit_transform(dane, target)

#sprawdzam nazwy wybranych kolumn
wybrane_kolumny = dane.columns[wybor_cech.get_support()].tolist()

print("Wybrane kolumny:")
for kolumna in wybrane_kolumny:
    print("-", kolumna)

#tworze nowy zbior danych
wynik = pd.DataFrame(nowe_dane, columns=wybrane_kolumny)
wynik["TARGET"] = target

print()
print("Wymiar danych po redukcji:", wynik.shape)

#zapis do csv
wynik.to_csv("dataset_algorithm.csv", sep=";", index=False)
print("Zapisano plik dataset_algorithm.csv")
print()

#podglad
display(wynik.head())

Wybrane kolumny:
- mean perimeter
- mean concave points
- worst radius
- worst perimeter
- worst concave points

Wymiar danych po redukcji: (569, 6)
Zapisano plik dataset_algorithm.csv

,mean perimeter,mean concave points,worst radius,worst perimeter,worst concave points,TARGET
0,122.80,0.14710,25.38,184.60,0.2654,0
1,132.90,0.07017,24.99,158.80,0.1860,0
2,130.00,0.12790,23.57,152.50,0.2430,0
3,77.58,0.10520,14.91,98.87,0.2575,0
4,135.10,0.10430,22.54,152.20,0.1625,0

W tym zadaniu wykorzystałem metode SelectKBest która wybiera najlepsze cechy na podstawie ich związku ze zmeinna target. Ustawiłem wybór 5 cech dzieki czemu liczba kolumn w zbiorze została zmniejszona i w zbiorze zostały tylko najbardziej istotne.